### ISSUE TITLE
Getting errors with references

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gmt-0010-2012#1]
@opoudjis this document is getting these errors on references. Could you help fix them (or asciidoctor-gb)? Thanks.

```
asciidoctor: WARNING(Section: 规范性引用文件): no anchor on reference: [<bookmark id="GBT162621"/>], 信息技术 抽象语法记法一（ASN.1）：基本记法规范(ISO/IEC 8824-1:2002，IDT)
asciidoctor: WARNING(Section: 规范性引用文件): no anchor on reference: [<bookmark id="GMT0006"/>], 密码应用标识规范
asciidoctor: WARNING(Section: 规范性引用文件): no anchor on reference: [<bookmark id="GMT0009"/>], SM2密码算法使用规范
asciidoctor: WARNING(Section: 规范性引用文件): no anchor on reference: [<bookmark id="PKCS6"/>] Extended Certificate Syntax
```

**Comment by opoudjis** [comment]
Notice that the error occurs only when you are generating gmt-0010-2012-zh.adoc, not gmt-0010-2012-en.adoc.

You've left out the `[bibliography]` style attribute in gmt-0010-2012-zh.adoc. Without it, bibliographic entries are not processed.

You've also left out the mandatory comma in:

````
* [[[PKCS6,PKCS #6]]] Extended Certificate Syntax
````

Please remember to close this ticket when done.

**Comment by ronaldtse** [comment]
Fixed, thanks!
